### ISSUE TITLE
Race condition on generate

### ISSUE THREAD

**Issue by timfpark** [Microsoft/fabrikate#148]
A recent CI/CD test on a documentation change uncovered a race condition:

```sh
=== RUN   TestGenerateJSON
time="2019-04-18T14:26:16Z" level=info msg="💾  Loading ../test/fixtures/generate/component.json"
time="2019-04-18T14:26:16Z" level=info msg="💾  Loading ../test/fixtures/generate/infra/component.json"
time="2019-04-18T14:26:16Z" level=info msg="💾  Loading ../test/fixtures/generate/infra/config/prod.json"
time="2019-04-18T14:26:16Z" level=info msg="💾  Loading ../test/fixtures/generate/infra/config/common.json"
time="2019-04-18T14:26:16Z" level=info msg="💾  Writing ../test/fixtures/generate/generated/prod-east-prod/microservices-workload.yaml"
time="2019-04-18T14:26:16Z" level=info msg="🙌  finished generate"
==================
WARNING: DATA RACE
Read at 0x00c0001ce130 by goroutine 12:
  runtime.chansend()
      /usr/local/go1.11/src/runtime/chan.go:140 +0x0
  github.com/Microsoft/fabrikate/core.WalkComponentTree.func5.1()
      /home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:286 +0x1d0

Previous write at 0x00c0001ce130 by goroutine 11:
  runtime.closechan()
      /usr/local/go1.11/src/runtime/chan.go:327 +0x0
  github.com/Microsoft/fabrikate/core.WalkComponentTree.func1()
      /home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:246 +0x285
  github.com/Microsoft/fabrikate/core.WalkComponentTree.func5.1.1.1()
      /home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:293 +0x139
  github.com/Microsoft/fabrikate/core.WalkComponentTree.func5.1.1()
      /home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:299 +0xf4

Goroutine 12 (running) created at:
  github.com/Microsoft/fabrikate/core.WalkComponentTree.func5()
      /home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:282 +0x14a

Goroutine 11 (running) created at:
  github.com/Microsoft/fabrikate/core.WalkComponentTree.func5.1()
      /home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:289 +0x20f
==================
panic: send on closed channel

goroutine 21 [running]:
github.com/Microsoft/fabrikate/core.WalkComponentTree.func5.1(0xc0001ce120, 0xbea2f8, 0xc000198480, 0xc000188450, 0xc0001984a0, 0xc00002ac88, 0x5, 0x0, 0x0, 0x0, ...)
	/home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:286 +0x1d1
created by github.com/Microsoft/fabrikate/core.WalkComponentTree.func5
	/home/vsts/work/1/s/gopath/src/github.com/Microsoft/fabrikate/core/component.go:282 +0x14b
FAIL	github.com/Microsoft/fabrikate/cmd	0.026s
```

I am running the tests on CI/CD with the -race flag:

```sh
$ go test -v -race ./...
```

**Comment by timfpark** [comment]
@evanlouie Potentially related to https://github.com/Microsoft/fabrikate/commit/458d280936e13aede6346c40f06b721f73bcda59
