### ISSUE TITLE
Error on non-string namespace property

### ISSUE THREAD

**Issue by edaena** [Microsoft/fabrikate#71]
**Context:** fabrikate-ambassador component
The namespace is specified like this: https://github.com/helm/charts/blob/master/stable/ambassador/values.yaml
```
namespace:
  single: false
  # name: default
```

**Steps:**
In common.yaml file:
```
config:
subcomponents:
  ambassador: 
    config:
      replicaCount: 3
      namespace:
        name: ambassador
```

`fab generate prod`

**Expected:** deployment.yaml is generated

**Seen:**            
```
INFO[25-02-2019 16:31:02] 💾  Loading config/common.yaml                
INFO[25-02-2019 16:31:02] 🚚  generating component 'fabrikate-ambassador' statically from path ./manifests 
INFO[25-02-2019 16:31:02] 🚚  generating component 'ambassador' with helm with repo https://github.com/helm/charts 
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/Microsoft/fabrikate/generators.(*HelmGenerator).Generate(0xcab0a8, 0xc00012a3c0, 0x0, 0x870bc0, 0x1, 0xcab0a8)
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/generators/helm.go:89 +0xba1
github.com/Microsoft/fabrikate/core.(*Component).Generate(0xc00012a3c0, 0x9709a0, 0xcab0a8, 0x2, 0x2)
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/core/component.go:217 +0xdd
github.com/Microsoft/fabrikate/cmd.Generate.func1(0x8e0808, 0x2, 0xc00012a3c0, 0x2, 0x2)
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/cmd/generate.go:68 +0x69
github.com/Microsoft/fabrikate/core.IterateComponentTree(0x8e0808, 0x2, 0xc0000472c0, 0x1, 0x1, 0x90e090, 0x32, 0xcabea0, 0x0, 0x600fb2, ...)
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/core/component.go:299 +0xcb8
github.com/Microsoft/fabrikate/cmd.Generate(0x8e0808, 0x2, 0xc0000472c0, 0x1, 0x1, 0xc000137c01, 0x652d40, 0xc000137cb8, 0xc000137c88, 0x0, ...)
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/cmd/generate.go:58 +0x80
github.com/Microsoft/fabrikate/cmd.glob..func1(0xc84ba0, 0xc0000472c0, 0x1, 0x1, 0x0, 0x0)
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/cmd/generate.go:106 +0x125
github.com/spf13/cobra.(*Command).execute(0xc84ba0, 0xc000047270, 0x1, 0x1, 0xc84ba0, 0xc000047270)
	/Users/evlouie/go/src/github.com/spf13/cobra/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc85060, 0x5847c6, 0xc000052270, 0x90e198)
	/Users/evlouie/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc85060, 0x5820d1, 0xc000052240)
	/Users/evlouie/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/Microsoft/fabrikate/cmd.Execute()
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/cmd/root.go:36 +0x2d
main.main()
	/Users/evlouie/go/src/github.com/Microsoft/fabrikate/main.go:15 +0x6c

```

**Comment by timfpark** [comment]
Interesting - this is because Fabrikate expects `namespace` to be a string because it has to manually rewrite namespaces in the generated resource manifests because of the way `helm template` (doesn't) works.
